server:
  port: 8010
  servlet:
    context-path: /api
spring:
#  关于热部署：开启以下配置就会实时重启，一般通过ctrl+f9即可重新加载
#  devtools:
#    restart:
#      enabled: true
##     设置重启目录
#      additionalPaths: src/main/java
#      设置不需要重启目录
#      exclude: META-INF/**,resources/**,static/**,public/**,templates/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mobilego?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  type-aliases-package: com.example.mobilego.entity
#  type-handlers-package: com.example.typehandler
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
mapper:
    mappers:
        - com.example.mobilego.support.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


logging:
  level:
    root: info
    com.example.mobilego.mapper: TRACE