server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mobilego?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
